// Generated by https://quicktype.io

export interface YoutubeChannel {
  kind: string;
  etag: string;
  pageInfo: PageInfo;
  items: YoutubeItem[];
}

export interface YoutubeItem {
  kind: ItemKind;
  etag: string;
  id: string;
  snippet: Snippet;
}

export enum ItemKind {
  YoutubePlaylistItem = "youtube#playlistItem",
}

export interface Snippet {
  publishedAt: string;
  channelId: ChannelID;
  title: string;
  description: Description;
  thumbnails: Thumbnails;
  channelTitle: ChannelTitle;
  playlistId: PlaylistID;
  position: number;
  resourceId: ResourceID;
}

export enum ChannelID {
  UCVMX9SEpU85YLcYNt2QeLA = "UC_VmX9sEpU85yLcYNt2qeLA",
}

export enum ChannelTitle {
  MiracleAssembly = "Miracle Assembly",
}

export enum Description {
  Empty = "",
  QualityLivingTV = "Quality Living TV",
  SeriesOnPerceptionVsRealityByPastorJeffreyIyonawan = "Series On Perception Vs Reality By Pastor Jeffrey Iyonawan",
}

export enum PlaylistID {
  PL58Tx4GWNzmvGbz8HjQdvDPGF6StQKf = "PL58tx4GWNzmvGbz8-hjQdvDP-gF6stQKf",
}

export interface ResourceID {
  kind: ResourceIDKind;
  videoId: string;
}

export enum ResourceIDKind {
  YoutubeVideo = "youtube#video",
}

export interface Thumbnails {
  default: Default;
  medium: Default;
  high: Default;
  standard: Default;
  maxres?: Default;
}

export interface Default {
  url: string;
  width: number;
  height: number;
}

export interface PageInfo {
  totalResults: number;
  resultsPerPage: number;
}
